# Generated by Django 3.0.2 on 2020-01-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='console',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
